-- 7.1 Final: align persisted format facets with SupportedFormatRegistry.
-- This immutable migration is a point-in-time compatibility snapshot; runtime detection remains registry-driven.
UPDATE books
SET format = CASE
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.fb2.zip' THEN 'ZIP'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.tar.gz' THEN 'TAR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.tar.bz2' THEN 'TAR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.tar.xz' THEN 'TAR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.fb2zip' THEN 'ZIP'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.fb2' THEN 'FB2'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.fbd' THEN 'FB2'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.epub' THEN 'EPUB'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.txt' OR LOWER(COALESCE(file_name, '')) LIKE '%.text' OR LOWER(COALESCE(file_name, '')) LIKE '%.md' THEN 'TXT'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.pdf' THEN 'PDF'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.mobi' THEN 'MOBI'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.azw3' OR LOWER(COALESCE(file_name, '')) LIKE '%.azw' THEN 'AZW3'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.djvu' OR LOWER(COALESCE(file_name, '')) LIKE '%.djv' THEN 'DJVU'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.docx' THEN 'DOCX'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.doc' THEN 'DOC'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.odt' THEN 'ODT'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.rtf' THEN 'RTF'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.xhtml' OR LOWER(COALESCE(file_name, '')) LIKE '%.html' OR LOWER(COALESCE(file_name, '')) LIKE '%.htm' THEN 'HTML'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.chm' THEN 'CHM'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.inpx' OR LOWER(COALESCE(file_name, '')) LIKE '%.inp' THEN 'INPX'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.cbz' THEN 'CBZ'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.jar' THEN 'JAR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.7z' THEN 'SEVEN_Z'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.rar' THEN 'RAR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.cbr' THEN 'CBR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.tgz' OR LOWER(COALESCE(file_name, '')) LIKE '%.tbz2' OR LOWER(COALESCE(file_name, '')) LIKE '%.txz' OR LOWER(COALESCE(file_name, '')) LIKE '%.tar' THEN 'TAR'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.cpio' THEN 'CPIO'
    WHEN LOWER(COALESCE(file_name, '')) LIKE '%.zip' THEN 'ZIP'
    ELSE 'UNKNOWN'
END;
